import type {
  Book,
  Author,
  Community,
  Event,
  ReaderStory,
  ReadingChallengeMonth,
  WellbeingTopic,
} from '@/types';

// ─────────────────────────────────────────────
// BOOKS
// ─────────────────────────────────────────────
export const books: Book[] = [
  {
    id: '1',
    slug: 'pather-panchali',
    title: 'পথের পাঁচালী',
    titleBn: 'পথের পাঁচালী',
    author: 'Bibhutibhushan Bandyopadhyay',
    authorSlug: 'bibhutibhushan-bandyopadhyay',
    genre: 'Bangla Literature',
    genres: ['Bangla Literature', 'Fiction', 'Classic'],
    description:
      'One of the greatest Bengali novels ever written, Pather Panchali follows young Apu and his sister Durga growing up in rural Bengal. A timeless story of childhood, poverty, beauty and the passage of time.',
    shortDescription: 'A timeless portrait of childhood in rural Bengal.',
    coverColor: '#2D5016',
    rating: 4.9,
    reviewCount: 3241,
    year: 1929,
    pages: 312,
    language: 'bangla',
    tags: ['classic', 'childhood', 'rural Bengal', 'family'],
    featured: true,
    whyRead:
      'An unparalleled exploration of innocence and beauty. Reading Pather Panchali is to understand the soul of Bengal.',
  },
  {
    id: '2',
    slug: 'lal-shobujer-pahad',
    title: 'লাল সবুজের পাহাড়',
    titleBn: 'লাল সবুজের পাহাড়',
    author: 'Humayun Ahmed',
    authorSlug: 'humayun-ahmed',
    genre: 'Bangla Literature',
    genres: ['Bangla Literature', 'Fiction'],
    description:
      'A moving narrative set against the backdrop of Bangladesh\'s Liberation War and the landscapes of the Chittagong Hill Tracts. Humayun Ahmed at his most reflective.',
    shortDescription: 'A reflective journey through Bangladesh\'s mountains and memory.',
    coverColor: '#8B2335',
    rating: 4.7,
    reviewCount: 1842,
    year: 1988,
    pages: 228,
    language: 'bangla',
    tags: ['Liberation War', 'Bangladesh', 'memory'],
    featured: true,
    trending: true,
  },
  {
    id: '3',
    slug: 'misir-ali-anisumer-mrittu',
    title: 'মিসির আলি আনিসুমের মৃত্যু',
    titleBn: 'মিসির আলি আনিসুমের মৃত্যু',
    author: 'Humayun Ahmed',
    authorSlug: 'humayun-ahmed',
    genre: 'Fiction',
    genres: ['Fiction', 'Mystery', 'Bangla Literature'],
    description:
      'Humayun Ahmed\'s beloved rationalist detective Misir Ali investigates a haunting case that blurs the line between psychology and the supernatural.',
    shortDescription: 'Bangladesh\'s most beloved detective meets his most puzzling case.',
    coverColor: '#1B3A5E',
    rating: 4.6,
    reviewCount: 2105,
    year: 1995,
    pages: 198,
    language: 'bangla',
    tags: ['mystery', 'detective', 'supernatural', 'psychology'],
    trending: true,
  },
  {
    id: '4',
    slug: 'ekattorer-dinguli',
    title: 'একাত্তরের দিনগুলি',
    titleBn: 'একাত্তরের দিনগুলি',
    author: 'Jahanara Imam',
    authorSlug: 'jahanara-imam',
    genre: 'Biography',
    genres: ['Biography', 'History', 'Bangladesh'],
    description:
      'The personal diary of Shaheed Janani Jahanara Imam, recounting the nine months of Bangladesh\'s Liberation War in 1971. One of the most important documents of Bangladeshi history.',
    shortDescription: 'An essential firsthand account of Bangladesh\'s Liberation War.',
    coverColor: '#5B3A1A',
    rating: 4.95,
    reviewCount: 4210,
    year: 1986,
    pages: 380,
    language: 'bangla',
    tags: ['Liberation War', '1971', 'history', 'diary', 'essential'],
    featured: true,
  },
  {
    id: '5',
    slug: 'sonar-deer',
    title: 'সোনার তরী',
    titleBn: 'সোনার তরী',
    author: 'Rabindranath Tagore',
    authorSlug: 'rabindranath-tagore',
    genre: 'Poetry',
    genres: ['Poetry', 'Bangla Literature', 'Classic'],
    description:
      'A landmark poetry collection by Rabindranath Tagore. The title poem is considered one of the greatest Bengali poems — a meditation on creation, time and the artist\'s relationship with their work.',
    shortDescription: 'Tagore\'s landmark collection featuring one of Bengali poetry\'s finest poems.',
    coverColor: '#7A5C00',
    rating: 4.8,
    reviewCount: 1932,
    year: 1894,
    pages: 148,
    language: 'bangla',
    tags: ['Tagore', 'poetry', 'classic', 'Nobel'],
    featured: true,
  },
  {
    id: '6',
    slug: 'bangladesher-itihas',
    title: 'বাংলাদেশের ইতিহাস',
    titleBn: 'বাংলাদেশের ইতিহাস',
    author: 'Sirajul Islam',
    authorSlug: 'sirajul-islam',
    genre: 'History',
    genres: ['History', 'Bangladesh', 'Non-Fiction'],
    description:
      'A comprehensive and authoritative history of Bangladesh from ancient times to the present day. Essential reading for understanding how Bangladesh came to be.',
    shortDescription: 'The definitive history of Bangladesh for general readers.',
    coverColor: '#1B5E3B',
    rating: 4.7,
    reviewCount: 987,
    year: 2012,
    pages: 520,
    language: 'bangla',
    tags: ['history', 'Bangladesh', 'essential', 'academic'],
    isNewRelease: false,
  },
  {
    id: '7',
    slug: 'the-reluctant-fundamentalist',
    title: 'The Reluctant Fundamentalist',
    author: 'Mohsin Hamid',
    authorSlug: 'mohsin-hamid',
    genre: 'English',
    genres: ['English', 'Fiction', 'Contemporary'],
    description:
      'A gripping monologue of a Pakistani man\'s journey from Princeton to Wall Street, and his eventual disillusionment with the West. Globally celebrated and widely read in Bangladesh.',
    shortDescription: 'A compelling examination of identity, belonging and the post-9/11 world.',
    coverColor: '#2C2C2C',
    rating: 4.4,
    reviewCount: 754,
    year: 2007,
    pages: 209,
    language: 'english',
    tags: ['contemporary fiction', 'identity', 'South Asia'],
    trending: true,
  },
  {
    id: '8',
    slug: 'tin-goyenda',
    title: 'তিন গোয়েন্দা',
    titleBn: 'তিন গোয়েন্দা',
    author: 'Rakib Hasan',
    authorSlug: 'rakib-hasan',
    genre: 'Children',
    genres: ['Children', 'Mystery', 'Fiction'],
    description:
      'The beloved Bangladeshi children\'s detective series following three young detectives solving mysteries. Generations of Bangladeshi children have grown up with Tin Goyenda.',
    shortDescription: 'Bangladesh\'s most beloved children\'s detective series.',
    coverColor: '#1B3A7A',
    rating: 4.8,
    reviewCount: 5621,
    year: 1990,
    pages: 162,
    language: 'bangla',
    tags: ['children', 'detective', 'series', 'adventure'],
    trending: true,
  },
  {
    id: '9',
    slug: 'nihar-ronjon-gupto-golpo',
    title: 'নীহার রঞ্জনের গোয়েন্দা গল্প',
    author: 'Nihar Ranjan Gupta',
    authorSlug: 'nihar-ranjan-gupta',
    genre: 'Fiction',
    genres: ['Fiction', 'Mystery', 'Bangla Literature'],
    description:
      'Classic Bengali detective stories featuring the legendary detective Kiriti Roy. Timeless mysteries set in colonial Bengal and beyond.',
    shortDescription: 'Classic detective stories with Bengal\'s legendary Kiriti Roy.',
    coverColor: '#4A1942',
    rating: 4.5,
    reviewCount: 1203,
    year: 1950,
    pages: 248,
    language: 'bangla',
    tags: ['detective', 'classic', 'mystery'],
    isNewRelease: false,
  },
  {
    id: '10',
    slug: 'jibonananda-das-kobita',
    title: 'জীবনানন্দ দাশের কবিতা',
    titleBn: 'জীবনানন্দ দাশের কবিতা',
    author: 'Jibanananda Das',
    authorSlug: 'jibanananda-das',
    genre: 'Poetry',
    genres: ['Poetry', 'Bangla Literature', 'Classic'],
    description:
      'The collected poetry of Jibanananda Das, widely considered the greatest Bengali poet after Tagore. His imagery of Bangla\'s rivers, fields and light is incomparable.',
    shortDescription: 'The finest Bengali poetry since Tagore — luminous and unforgettable.',
    coverColor: '#2C5F2E',
    rating: 4.9,
    reviewCount: 2891,
    year: 1954,
    pages: 290,
    language: 'bangla',
    tags: ['poetry', 'classic', 'Jibanananda', 'essential'],
    featured: true,
  },
  {
    id: '11',
    slug: 'atomic-habits-bangla',
    title: 'অ্যাটমিক হ্যাবিটস',
    titleBn: 'অ্যাটমিক হ্যাবিটস',
    author: 'James Clear (অনুবাদ)',
    authorSlug: 'james-clear',
    genre: 'Personal Growth',
    genres: ['Personal Growth', 'Non-Fiction'],
    description:
      'The Bangla translation of James Clear\'s global bestseller on building good habits and breaking bad ones. Practical, evidence-based and deeply readable.',
    shortDescription: 'The world\'s most popular guide to building better habits — now in Bangla.',
    coverColor: '#D4580A',
    rating: 4.7,
    reviewCount: 3102,
    year: 2022,
    pages: 326,
    language: 'bangla',
    tags: ['self-help', 'habits', 'productivity', 'translation'],
    isNewRelease: true,
    trending: true,
  },
  {
    id: '12',
    slug: 'muktijoddhar-diary',
    title: 'মুক্তিযোদ্ধার ডায়েরি',
    titleBn: 'মুক্তিযোদ্ধার ডায়েরি',
    author: 'Various Authors',
    authorSlug: 'various',
    genre: 'Bangladesh',
    genres: ['Bangladesh', 'History', 'Biography'],
    description:
      'A powerful collection of firsthand testimonies and diaries from freedom fighters of the 1971 Liberation War. Raw, honest and historically invaluable.',
    shortDescription: 'Firsthand testimonies from the freedom fighters of 1971.',
    coverColor: '#7A0000',
    rating: 4.8,
    reviewCount: 1456,
    year: 2021,
    pages: 412,
    language: 'bangla',
    tags: ['Liberation War', '1971', 'testimony', 'Bangladesh', 'essential'],
    isNewRelease: true,
    featured: true,
  },
];

export const featuredBooks = books.filter((b) => b.featured);
export const trendingBooks = books.filter((b) => b.trending);
export const newReleases = books.filter((b) => b.isNewRelease);

// ─────────────────────────────────────────────
// AUTHORS
// ─────────────────────────────────────────────
export const authors: Author[] = [
  {
    id: '1',
    slug: 'humayun-ahmed',
    name: 'Humayun Ahmed',
    nameBn: 'হুমায়ূন আহমেদ',
    genre: 'Fiction',
    genres: ['Fiction', 'Science Fiction', 'Drama', 'Children'],
    biography:
      'Humayun Ahmed (1948–2012) is arguably the most widely read Bangladeshi author of all time. A novelist, playwright, filmmaker and songwriter, he transformed Bangladeshi popular literature. His characters — Himu, Misir Ali, Baker Bhai — have become cultural icons. He wrote over 200 books and directed several acclaimed films, all while remaining fiercely independent.',
    shortBio:
      'Bangladesh\'s most beloved storyteller and cultural icon. Creator of Himu and Misir Ali.',
    bookCount: 200,
    location: 'Dhaka, Bangladesh',
    featured: true,
    awards: ['Bangla Academy Award', 'Ekushey Padak', 'National Film Award'],
    specialization: 'Popular Fiction & Drama',
  },
  {
    id: '2',
    slug: 'jahanara-imam',
    name: 'Jahanara Imam',
    nameBn: 'জাহানারা ইমাম',
    genre: 'Non-Fiction',
    genres: ['Non-Fiction', 'Biography', 'History'],
    biography:
      'Jahanara Imam (1929–1994), known as Shaheed Janani (Mother of Martyrs), lost her son Rumi in the Liberation War of 1971. Her diary of that year, "Ekattorer Dinguli," is one of the most important documents in Bangladeshi literature. She went on to lead the Ghatak Dalal Nirmul Committee, demanding justice for war crimes.',
    shortBio:
      '"Shaheed Janani" — the mother of martyrs. Her Liberation War diary is essential reading.',
    bookCount: 12,
    location: 'Dhaka, Bangladesh',
    featured: true,
    awards: ['Ekushey Padak (posthumous)', 'Independence Day Award'],
    specialization: 'Liberation War Literature',
  },
  {
    id: '3',
    slug: 'anisul-haque',
    name: 'Anisul Haque',
    nameBn: 'আনিসুল হক',
    genre: 'Fiction',
    genres: ['Fiction', 'Non-Fiction', 'Children', 'Drama'],
    biography:
      'Anisul Haque is one of Bangladesh\'s most prolific and commercially successful living authors. His novel "Ma" — about a mother searching for her son during the Liberation War — became a landmark bestseller. He is also a celebrated journalist and playwright.',
    shortBio: 'Author of "Ma" and one of Bangladesh\'s most beloved living writers.',
    bookCount: 80,
    location: 'Dhaka, Bangladesh',
    featured: true,
    awards: ['Bangla Academy Award', 'Prothom Alo Award'],
    specialization: 'Fiction & Social Drama',
  },
  {
    id: '4',
    slug: 'syed-shamsul-haq',
    name: 'Syed Shamsul Haq',
    nameBn: 'সৈয়দ শামসুল হক',
    genre: 'Poetry',
    genres: ['Poetry', 'Fiction', 'Drama', 'Bangla Literature'],
    biography:
      'Syed Shamsul Haq (1935–2016), often called Shob Jadur Raja (King of All Arts), was equally accomplished as a poet, novelist, playwright and lyricist. His verse play "Nuruldiner Shara Jibon" is a masterpiece of Bengali literature. He received virtually every major literary award Bangladesh offers.',
    shortBio: '"King of All Arts" — poet, novelist, playwright and lyricist of extraordinary range.',
    bookCount: 150,
    location: 'Dhaka, Bangladesh',
    featured: true,
    awards: ['Bangla Academy Award', 'Ekushey Padak', 'Independence Day Award'],
    specialization: 'Poetry, Drama & Fiction',
  },
  {
    id: '5',
    slug: 'tahmima-anam',
    name: 'Tahmima Anam',
    nameBn: 'তাহমিমা আনাম',
    genre: 'English',
    genres: ['English', 'Fiction', 'Contemporary'],
    biography:
      'Tahmima Anam is a Bangladeshi novelist writing in English. Her Bengal Trilogy — beginning with "A Golden Age" — tells the story of Bangladesh\'s formation through three generations. She has been recognized as one of the most important voices in contemporary South Asian literature.',
    shortBio: 'Author of "A Golden Age" and Bangladesh\'s foremost voice in English literary fiction.',
    bookCount: 4,
    location: 'London / Dhaka',
    isNewVoice: false,
    featured: true,
    awards: ['Daily Telegraph Fiction Prize', 'Commonwealth Writers\' Prize shortlist'],
    specialization: 'English Literary Fiction',
    social: { website: 'https://tahminaanam.com' },
  },
  {
    id: '6',
    slug: 'shahaduzzaman',
    name: 'Shahaduzzaman',
    nameBn: 'শাহাদুজ্জামান',
    genre: 'Fiction',
    genres: ['Fiction', 'Short Stories', 'Biography'],
    biography:
      'Shahaduzzaman is a distinctive voice in contemporary Bangladeshi literature. His fiction blends the political and the personal with understated precision. His biography of Amar Mitra and his story collections have earned wide critical acclaim.',
    shortBio: 'One of Bangladesh\'s most distinctive voices in contemporary literary fiction.',
    bookCount: 18,
    location: 'Dhaka, Bangladesh',
    isNewVoice: true,
    awards: ['Bangla Academy Award'],
    specialization: 'Literary Fiction & Short Stories',
  },
  {
    id: '7',
    slug: 'mashiur-rahman',
    name: 'Mashiur Rahman Biplob',
    nameBn: 'মাশিউর রহমান বিপ্লব',
    genre: 'Science',
    genres: ['Science', 'Non-Fiction', 'Popular Science'],
    biography:
      'Mashiur Rahman Biplob has made popular science accessible to Bangladeshi readers. His writing introduces complex scientific ideas in clear, engaging Bangla prose, inspiring a generation of young Bangladeshis to explore the natural world through books.',
    shortBio: 'Making science accessible and exciting for Bangladeshi readers.',
    bookCount: 22,
    location: 'Chittagong, Bangladesh',
    isEmerging: true,
    specialization: 'Popular Science',
  },
  {
    id: '8',
    slug: 'nazma-khan',
    name: 'Nazma Khan',
    nameBn: 'নাজমা খান',
    genre: 'Children',
    genres: ['Children', 'Fiction', 'Poetry'],
    biography:
      'Nazma Khan writes for children in a tradition that combines imagination with the textures of Bangladeshi everyday life. Her picture books and early-reader stories are recommended by schools across the country.',
    shortBio: 'Writing joyful, imaginative books for the next generation of Bangladeshi readers.',
    bookCount: 14,
    location: 'Sylhet, Bangladesh',
    isEmerging: true,
    specialization: 'Children\'s Literature',
  },
];

export const featuredAuthors = authors.filter((a) => a.featured);
export const newVoices = authors.filter((a) => a.isNewVoice);
export const emergingWriters = authors.filter((a) => a.isEmerging);

// ─────────────────────────────────────────────
// COMMUNITIES
// ─────────────────────────────────────────────
export const communities: Community[] = [
  {
    id: '1',
    name: 'Dhaka Readers',
    nameBn: 'ঢাকা রিডার্স',
    location: 'Dhaka',
    members: 342,
    currentBook: 'একাত্তরের দিনগুলি',
    currentBookAuthor: 'Jahanara Imam',
    nextMeeting: 'October 5, 2026 — Dhanmondi Public Library',
    description: 'Dhaka\'s oldest and largest reading community, bringing together readers across the city for monthly book discussions and author meetings.',
    tags: ['Dhaka', 'All Genres', 'Monthly Meetups'],
    coverColor: '#1B5E3B',
  },
  {
    id: '2',
    name: 'Chittagong Book Circle',
    nameBn: 'চট্টগ্রাম বুক সার্কেল',
    location: 'Chittagong',
    members: 187,
    currentBook: 'পথের পাঁচালী',
    currentBookAuthor: 'Bibhutibhushan Bandyopadhyay',
    nextMeeting: 'October 8, 2026 — Chittagong City Corporation Library',
    description: 'A vibrant community of readers in Chittagong passionate about both Bangla and English literature.',
    tags: ['Chittagong', 'Literature', 'Bi-weekly'],
    coverColor: '#8B2335',
  },
  {
    id: '3',
    name: 'University Readers Bangladesh',
    nameBn: 'বিশ্ববিদ্যালয় রিডার্স বাংলাদেশ',
    location: 'Nationwide',
    members: 891,
    currentBook: 'Sapiens',
    currentBookAuthor: 'Yuval Noah Harari',
    nextMeeting: 'October 12, 2026 — Online',
    description: 'Connecting students across Bangladeshi universities through shared reading. Chapters at DU, BUET, BRAC, NSU and beyond.',
    tags: ['University', 'Students', 'Online + In-person'],
    coverColor: '#1B3A5E',
  },
  {
    id: '4',
    name: 'Young Readers Club',
    nameBn: 'ইয়ং রিডার্স ক্লাব',
    location: 'Dhaka',
    members: 256,
    currentBook: 'Harry Potter and the Philosopher\'s Stone',
    currentBookAuthor: 'J.K. Rowling',
    nextMeeting: 'October 4, 2026 — Gulshan Community Center',
    description: 'A welcoming community for readers aged 16–30 exploring fiction, ideas and everything in between.',
    tags: ['Young Adults', 'Fiction', 'Dhaka'],
    coverColor: '#4A1942',
  },
  {
    id: '5',
    name: 'Bangla Literature Circle',
    nameBn: 'বাংলা সাহিত্য সার্কেল',
    location: 'Multiple Cities',
    members: 423,
    currentBook: 'জীবনানন্দ দাশের কবিতা',
    currentBookAuthor: 'Jibanananda Das',
    nextMeeting: 'October 15, 2026 — Bangla Academy, Dhaka',
    description: 'Dedicated to celebrating and preserving Bangla literary tradition while discovering new voices.',
    tags: ['Bangla', 'Poetry', 'Classic & Contemporary'],
    coverColor: '#5B3A1A',
  },
  {
    id: '6',
    name: 'Children\'s Reading Community',
    nameBn: 'শিশু পাঠক সমাজ',
    location: 'Dhaka & Chittagong',
    members: 312,
    currentBook: 'তিন গোয়েন্দা',
    currentBookAuthor: 'Rakib Hasan',
    nextMeeting: 'October 6, 2026 — Shishu Academy, Dhaka',
    description: 'Parents and educators creating joyful reading experiences for children ages 5–14.',
    tags: ['Children', 'Parents', 'Education'],
    coverColor: '#D4580A',
  },
];

// ─────────────────────────────────────────────
// EVENTS
// ─────────────────────────────────────────────
export const events: Event[] = [
  {
    id: '1',
    slug: 'anisul-haque-author-meet',
    title: 'An Evening with Anisul Haque',
    titleBn: 'আনিসুল হকের সাথে একটি সন্ধ্যা',
    date: '2026-10-08',
    time: '5:00 PM',
    location: 'Dhaka',
    venue: 'Bangla Academy Auditorium',
    category: 'Author Meet',
    speaker: 'Anisul Haque',
    description: 'An intimate conversation with one of Bangladesh\'s most beloved authors on storytelling, memory and the role of fiction in a changing Bangladesh.',
    tags: ['fiction', 'author talk', 'Dhaka'],
    isFeatured: true,
  },
  {
    id: '2',
    slug: 'liberation-war-literature-symposium',
    title: 'Literature of Liberation: 1971 in Words',
    titleBn: 'মুক্তিযুদ্ধের সাহিত্য: শব্দে ১৯৭১',
    date: '2026-10-16',
    time: '10:00 AM',
    location: 'Dhaka',
    venue: 'Liberation War Museum',
    category: 'Literary Discussion',
    description: 'A daylong symposium exploring how Bangladeshi writers have captured the Liberation War across five decades. Panels, readings and archive screenings.',
    tags: ['Liberation War', '1971', 'history', 'literature'],
    isFeatured: true,
  },
  {
    id: '3',
    slug: 'young-writers-workshop',
    title: 'Young Writers Workshop: Finding Your Voice',
    titleBn: 'তরুণ লেখক কর্মশালা',
    date: '2026-10-22',
    time: '2:00 PM',
    location: 'Dhaka',
    venue: 'British Council Bangladesh',
    category: 'Writing Workshop',
    description: 'A practical workshop for aspiring writers aged 18–30. Explore narrative techniques, character development and the craft of writing in Bangla and English.',
    tags: ['writing', 'workshop', 'young adults'],
    isFeatured: false,
  },
  {
    id: '4',
    slug: 'tahmima-anam-book-launch',
    title: 'Book Launch: New Novel by Tahmima Anam',
    date: '2026-11-03',
    time: '6:00 PM',
    location: 'Dhaka',
    venue: 'Alliance Française de Dhaka',
    category: 'Book Launch',
    speaker: 'Tahmima Anam',
    description: 'The Dhaka launch of Tahmima Anam\'s eagerly anticipated new novel. Join the author for a reading, conversation and signing.',
    tags: ['book launch', 'English fiction', 'Tahmima Anam'],
    isFeatured: true,
  },
  {
    id: '5',
    slug: 'school-reading-day-sylhet',
    title: 'National Reading Day — Sylhet Schools',
    titleBn: 'জাতীয় পাঠ দিবস — সিলেট',
    date: '2026-10-28',
    time: '9:00 AM',
    location: 'Sylhet',
    venue: 'Multiple Schools, Sylhet',
    category: 'School Event',
    description: 'PoraBangla\'s National Reading Day initiative brings books and authors into schools across Sylhet. Students read together, share stories and meet local writers.',
    tags: ['schools', 'children', 'National Reading Day', 'Sylhet'],
    isFeatured: false,
  },
  {
    id: '6',
    slug: 'poetry-evening-chittagong',
    title: 'A Night of Bengali Poetry',
    titleBn: 'বাংলা কবিতার সন্ধ্যা',
    date: '2026-11-14',
    time: '6:30 PM',
    location: 'Chittagong',
    venue: 'Chittagong Shilpakala Academy',
    category: 'Reading Circle',
    description: 'Poets and readers gather to recite and celebrate the finest Bengali poetry — from Tagore and Jibanananda to the new generation of Bangladeshi voices.',
    tags: ['poetry', 'Chittagong', 'evening event'],
    isFeatured: false,
  },
  {
    id: '7',
    slug: 'university-reading-festival-dhaka',
    title: 'DU Reading Festival 2026',
    titleBn: 'ঢাবি পাঠ উৎসব ২০২৬',
    date: '2026-11-20',
    time: '10:00 AM',
    location: 'Dhaka',
    venue: 'Dhaka University Campus',
    category: 'University Event',
    description: 'A two-day festival of reading, writing and ideas at Dhaka University — featuring author talks, book fairs, writing competitions and reading circles.',
    tags: ['university', 'festival', 'Dhaka University'],
    isFeatured: true,
  },
];

// ─────────────────────────────────────────────
// READER STORIES
// ─────────────────────────────────────────────
export const readerStories: ReaderStory[] = [
  {
    id: '1',
    name: 'Farhan Hossain',
    age: 27,
    category: 'Graduate Student',
    location: 'Dhaka',
    quote: 'I stopped reading after I started university. I thought books were only for people with free time. Then a friend gave me Humayun Ahmed and I stayed up all night. I have not stopped since.',
  },
  {
    id: '2',
    name: 'Nusrat Jahan',
    age: 34,
    category: 'Teacher',
    location: 'Chittagong',
    quote: 'My mother gave me my first book when I was eight years old. That book opened a door I have never been able to close. I now share that same gift with my students.',
  },
  {
    id: '3',
    name: 'Arif Mahmud',
    age: 22,
    category: 'University Student',
    location: 'Rajshahi',
    quote: 'Books introduced me to worlds I had never seen — histories I was not taught in school, perspectives that challenged me, lives completely different from my own. That is irreplaceable.',
  },
  {
    id: '4',
    name: 'Sabrina Islam',
    age: 41,
    category: 'Architect',
    location: 'Dhaka',
    quote: 'Reading before sleep changed how I rest. I used to scroll my phone until midnight. Now I read. I sleep better, I think more clearly and I remember what matters.',
  },
  {
    id: '5',
    name: 'Tanvir Rashid',
    age: 19,
    category: 'School Student',
    location: 'Sylhet',
    quote: 'I joined a reading club expecting it to be boring. Instead I met the most interesting people I know. We argue about books for hours. I love it.',
  },
  {
    id: '6',
    name: 'Dilruba Akter',
    age: 55,
    category: 'Retired Teacher',
    location: 'Comilla',
    quote: 'In 1971, books were how we kept our culture alive. Even during the worst months, people passed books between themselves. Reading is how a people survive.',
  },
];

// ─────────────────────────────────────────────
// READING CHALLENGE MONTHS
// ─────────────────────────────────────────────
export const readingChallengeMonths: ReadingChallengeMonth[] = [
  { month: 1, monthName: 'January', monthNameBn: 'জানুয়ারি', theme: 'Fiction', themeBn: 'কল্পকাহিনী', description: 'Lose yourself in a great story.' },
  { month: 2, monthName: 'February', monthNameBn: 'ফেব্রুয়ারি', theme: 'Biography', themeBn: 'জীবনী', description: 'Discover an extraordinary life.' },
  { month: 3, monthName: 'March', monthNameBn: 'মার্চ', theme: 'Science', themeBn: 'বিজ্ঞান', description: 'Explore the natural world through books.' },
  { month: 4, monthName: 'April', monthNameBn: 'এপ্রিল', theme: 'History', themeBn: 'ইতিহাস', description: 'Understand how the present was made.' },
  { month: 5, monthName: 'May', monthNameBn: 'মে', theme: 'Poetry', themeBn: 'কবিতা', description: 'Read slowly. Feel every word.' },
  { month: 6, monthName: 'June', monthNameBn: 'জুন', theme: 'Bangladesh Literature', themeBn: 'বাংলাদেশের সাহিত্য', description: 'Discover the richness of our own tradition.' },
  { month: 7, monthName: 'July', monthNameBn: 'জুলাই', theme: 'Philosophy', themeBn: 'দর্শন', description: 'Question everything.' },
  { month: 8, monthName: 'August', monthNameBn: 'আগস্ট', theme: 'A Book in Translation', themeBn: 'অনুবাদ সাহিত্য', description: 'Read the world through another language.' },
  { month: 9, monthName: 'September', monthNameBn: 'সেপ্টেম্বর', theme: 'Children\'s Classic', themeBn: 'শিশু সাহিত্য', description: 'Revisit a book that shaped you.' },
  { month: 10, monthName: 'October', monthNameBn: 'অক্টোবর', theme: 'Non-Fiction', themeBn: 'প্রামাণিক সাহিত্য', description: 'Learn something genuinely new.' },
  { month: 11, monthName: 'November', monthNameBn: 'নভেম্বর', theme: 'Personal Growth', themeBn: 'ব্যক্তিগত উন্নয়ন', description: 'A book that challenges how you live.' },
  { month: 12, monthName: 'December', monthNameBn: 'ডিসেম্বর', theme: 'Your Choice', themeBn: 'আপনার পছন্দ', description: 'Finish the year with a book that matters to you.' },
];

// ─────────────────────────────────────────────
// WELLBEING TOPICS
// ─────────────────────────────────────────────
export const wellbeingTopics: WellbeingTopic[] = [
  {
    id: '1',
    title: 'Reading & Focus',
    description: 'Deep reading trains sustained attention in a world of constant distraction. Building a reading habit can help restore your capacity to think carefully.',
    icon: 'target',
    color: '#1B5E3B',
  },
  {
    id: '2',
    title: 'Reading & Digital Balance',
    description: 'Books offer a different rhythm to screen time — slower, more deliberate and restorative. Many readers find physical books a meaningful break from devices.',
    icon: 'smartphone',
    color: '#8B2335',
  },
  {
    id: '3',
    title: 'Reading Before Sleep',
    description: 'Reading before bed is a well-established evening ritual that many find helps them wind down and prepare for rest — replacing the stimulation of screens.',
    icon: 'moon',
    color: '#1B3A5E',
  },
  {
    id: '4',
    title: 'Reading With Children',
    description: 'Reading aloud to children is one of the most meaningful things a parent, grandparent or teacher can do. It builds vocabulary, imagination and the love of stories.',
    icon: 'heart',
    color: '#D4580A',
  },
  {
    id: '5',
    title: 'Reading & Creativity',
    description: 'Reading widely — especially fiction — exposes you to different perspectives, narrative structures and ways of thinking that can enrich your own creative work.',
    icon: 'sparkles',
    color: '#7A5C00',
  },
  {
    id: '6',
    title: 'Reading & Personal Growth',
    description: 'From biographies to philosophy to practical guides, books are one of the most efficient ways to learn from people and experiences far beyond your own.',
    icon: 'trending-up',
    color: '#4A1942',
  },
];

// ─────────────────────────────────────────────
// BOOK CATEGORIES
// ─────────────────────────────────────────────
export const bookCategories = [
  'All',
  'Bangla Literature',
  'English',
  'Fiction',
  'Non-Fiction',
  'History',
  'Science',
  'Biography',
  'Poetry',
  'Children',
  'Personal Growth',
  'Bangladesh',
];

// ─────────────────────────────────────────────
// EVENT CATEGORIES
// ─────────────────────────────────────────────
export const eventCategories = [
  'All',
  'Author Meet',
  'Book Launch',
  'Reading Circle',
  'Writing Workshop',
  'Literary Discussion',
  'School Event',
  'University Event',
];
